# image will be published to ghcr.io/<user>/<name>
name: base-main
# description will be included in the image's metadata
description: A uBlue base image build

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - vim
      - cockpit
      - cockpit-ostree
      - cockpit-podman
      - cronie
      - offlineimap
      - perl-Image-ExifTool
      - postfix
      - python3-pip
      - samba
      - rsyslog
      - nethogs
    remove:
      - firefox
      - firefox-langpacks
      - open-sans-fonts
      - google-noto-sans-thai-vf-fonts
      - google-noto-sans-thaana-vf-fonts
      # xorg driver need remvoving together
      - xorg-x11-server-Xorg
      - xorg-x11-server-Xwayland
      - xorg-x11-drv-amdgpu
      - xorg-x11-drv-ati
      - xorg-x11-drv-evdev
      - xorg-x11-drv-fbdev
      - xorg-x11-drv-intel
      - xorg-x11-drv-libinput
      - xorg-x11-drv-nouveau
      - xorg-x11-drv-openchrome
      - xorg-x11-drv-qxl
      - xorg-x11-drv-vesa
      - xorg-x11-drv-vmware
      - xorg-x11-drv-wacom
      #  gstreamer
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-qt
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-libs
      - gstreamer1-plugins-ugly-free
      - gstreamer1-plugin-libav 
      - pipewire-gstreamer
      - tracker-miners
      - ibus-gtk4
      - gtk4
      # qt5
      - qt5-qtbase
      - qt5-qtbase-common
      - qt5-qtbase-gui
      - qt5-qtgraphicaleffects
      - qt5-qtquickcontrols2
      - qt5-qtwayland
      - qt5-qtdeclarative
      - qt5-qtx11extras
      - qt5-qtxmlpatterns 
      - adwaita-qt5
      - qgnomeplatform-qt5
      - libadwaita-qt5
      # ibus
      - ibus
      - ibus-anthy
      - ibus-anthy-python
      - ibus-gtk3
      - ibus-hangul
      - ibus-libpinyin
      - ibus-libzhuyin
      - ibus-m17n
      - ibus-setup
      - ibus-typing-booster

  - type: signing # this sets up the proper policy & signing files for signed images to work fully