# image will be published to ghcr.io/<user>/<name>
name: kinoite-main
# description will be included in the image's metadata
description: A uBlue Kinoite build with some tools

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      - gwenview
      - digikam
      - skanlite
      - okular
      - ksystemlog
      - isoimagewriter
      - vlc
      - kid3
      - distrobox
      - minicom
      - vim
      - code
      - nethogs
      - printer-driver-brlaser
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
